ALTER TABLE NEWS ADD USERID BIGINT REFERENCES USERS (ID);
UPDATE NEWS SET USERID=1;
ALTER TABLE NEWS ALTER COLUMN USERID SET NOT NULL;

ALTER TABLE ADS ADD USERID BIGINT REFERENCES USERS (ID);
UPDATE ADS SET USERID=1;
ALTER TABLE ADS ALTER COLUMN USERID SET NOT NULL;

ALTER TABLE ADS ADD ISRELATEDTONEWS BOOLEAN DEFAULT FALSE NOT NULL;

CREATE TABLE CONTENT_PROVIDERS (ID BIGSERIAL NOT NULL, NAME TEXT NOT NULL,PRIMARY KEY(ID));

ALTER TABLE NEWS ADD PROVIDERID BIGINT REFERENCES CONTENT_PROVIDERS(ID);

ALTER TABLE ADS ADD TITLE TEXT;
ALTER TABLE ADS ADD SHORT_DESCRIPTION TEXT;

ALTER TABLE CATEGORIES ADD TRANSLATION TEXT;

ALTER TABLE DEVICES ADD NAME TEXT;