CREATE TABLE CONTENT_PROVIDER_CATEGORY (CONTENTPROVIDERID BIGINT REFERENCES CONTENT_PROVIDERS(ID) NOT NULL, CATEGORYID BIGINT REFERENCES CATEGORIES(ID) NOT NULL, PRIMARY KEY (CONTENTPROVIDERID,CATEGORYID));

ALTER TABLE AD_DISPLAY ADD PERCENTAGE INT;
UPDATE AD_DISPLAY SET PERCENTAGE=100;
ALTER TABLE AD_DISPLAY ALTER COLUMN PERCENTAGE SET NOT NULL;

CREATE TABLE GCM_TOKENS(ID BIGSERIAL NOT NULL,DEVICEID BIGINT REFERENCES DEVICES(ID) NOT NULL,TOKEN TEXT UNIQUE NOT NULL,PRIMARY KEY(ID));
CREATE INDEX DEVICE_GCM_INDEX ON GCM_TOKENS(DEVICEID);