CREATE TABLE CORPORATIONS(ID SERIAL NOT NULL,NAME TEXT,PRIMARY KEY(ID));
CREATE TABLE DEVICES(ID SERIAL NOT NULL, PHONE_NUMBER TEXT UNIQUE NOT NULL,CHARGE INT NOT NULL DEFAULT 0,PRIMARY KEY (ID));
CREATE TABLE ADS(ID SERIAL NOT NULL, PRICE TEXT,LINK TEXT, PHONE TEXT, LOCATION TEXT,
CORPORATIONID INT REFERENCES CORPORATIONS(ID), PRIMARY KEY (ID));
create index corporation_index on ads (corporationid);
CREATE TABLE AD_DISPLAY(ID SERIAL NOT NULL,SHOWDATE TIMESTAMP NOT NULL,SHOWN_TIME INT,ADID INT REFERENCES ADS(ID) NOT NULL,DEVICEID INT REFERENCES DEVICES(ID) NOT NULL,PRIMARY KEY (ID));
CREATE INDEX AD_INDEX ON AD_DISPLAY (ADID);
CREATE INDEX AD_SHOWN_TIME_INDEX ON AD_DISPLAY(SHOWN_TIME);
CREATE INDEX AD_SHOEN_DEVICE_INDEX ON AD_DISPLAY(DEVICEID);
CREATE TABLE DEALER_CORPORATIONS(ID SERIAL NOT NULL,NAME TEXT,PRIMARY KEY(ID));
CREATE TABLE MARKET_CONTENTS(ID SERIAL NOT NULL, PRICE TEXT,CONTENT BYTEA,
DEALERCORPORATIONID INT REFERENCES DEALER_CORPORATIONS(ID),CONTENT_TYPE TEXT, PRIMARY KEY (ID));
CREATE INDEX DEALER_CORPORATION_INDEX ON MARKET_CONTENTS(DEALERCORPORATIONID);

CREATE TABLE PURCHASES(ID SERIAL NOT NULL,PURCHASE_DATE TIMESTAMP NOT NULL,CONTENTID INT REFERENCES MARKET_CONTENTS(ID) NOT NULL,DEVICEID INT REFERENCES DEVICES(ID) NOT NULL,PRIMARY KEY (ID));
CREATE INDEX MARKET_CONTENT_PURCHASE_INDEX ON PURCHASES(CONTENTID);
CREATE INDEX DEVICE_ID_INDEX ON PURCHASES(DEVICEID);